licenses(["notice"])

exports_files(
    [
        "BUILD.dm_env",
        "BUILD.dm_env_rpc",
        "BUILD.highwayhash",
        "BUILD.net_zstd",
        "BUILD.snappy",
        "grpc.patch",
        "protobuf.patch",
        "requirements.txt",
        "s2clientprotocol.patch",
    ],
    visibility = ["//visibility:public"],
)
