# AlphaStar Unplugged - Offline Reinforcement Learning for Starcraft.

load("//alphastar:pytype.bzl", "pytype_strict_library")

licenses(["notice"])

pytype_strict_library(
    name = "__init__",
    srcs = ["__init__.py"],
)
