# BUILD file used to specify that the sources in this package are ignored, i.e.
# these files are only used in the opensource world.

licenses(["notice"])

exports_files([
    "leakr_badwords.dic",
])
